#!/bin/tcsh

set file=$1

if (!(-e $1)) then
   echo "Could not find file '" $1 "'"
   exit(-1)
endif

set cmd="gnuplot.scr"
cat > $cmd << END
set data style linespoints
set xlabel 'density (rs)'
set xrange [3.06:1.60]
set ylabel 'r/2rs'
set title 'diff'
plot "$file" u 1:( (\$3 - \$2)/(\$1*0.529177*2))

pause -1 "Showing $file diff.\nPress enter to quit"

set title 'ratio'
plot "$file" u 1:(\$3/\$2)

pause -1 "Showing $file ratio.\nPress enter to quit"

quit
END


gnuplot $cmd

#rm $cmd
