#!/bin/tcsh

set file=$1

if (!(-e $1)) then
   echo "Could not find file '" $1 "'"
   exit(-1)
endif

set cmd="gnuplot.scr"
cat > $cmd << END
set data style linespoints
set xrange [1:3.06]
set nokey
plot \
"$file" u 1:2,"$file" u 1:3,"$file" u 1:4,"$file" u 1:5,"$file" u 1:6,"$file" u 1:7,"$file" u 1:8,  \
"$file" u 1:9,"$file" u 1:10,"$file" u 1:11,"$file" u 1:12,"$file" u 1:13,"$file" u 1:14,"$file" u 1:15, \
"$file" u 1:16,"$file" u 1:17,"$file" u 1:18,"$file" u 1:19,"$file" u 1:20,"$file" u 1:21,"$file" u 1:22, \
"$file" u 1:23,"$file" u 1:24,"$file" u 1:25,"$file" u 1:26,"$file" u 1:27,"$file" u 1:28,"$file" u 1:29, \
"$file" u 1:30,"$file" u 1:31,"$file" u 1:32,"$file" u 1:33,"$file" u 1:34,"$file" u 1:35,"$file" u 1:36, \
"$file" u 1:37,"$file" u 1:38,"$file" u 1:39,"$file" u 1:40,"$file" u 1:41,"$file" u 1:42,"$file" u 1:43, \
"$file" u 1:44,"$file" u 1:45,"$file" u 1:46,"$file" u 1:47,"$file" u 1:48,"$file" u 1:49,"$file" u 1:50, \
"$file" u 1:51,"$file" u 1:52,"$file" u 1:53,"$file" u 1:54,"$file" u 1:55,"$file" u 1:56,"$file" u 1:57

#"$file" u 1:58,"$file" u 1:59,"$file" u 1:60,"$file" u 1:61,"$file" u 1:62,"$file" u 1:63,"$file" u 1:64, \
"$file" u 1:65,"$file" u 1:66,"$file" u 1:67,"$file" u 1:68,"$file" u 1:69,"$file" u 1:70,"$file" u 1:71, \
"$file" u 1:72,"$file" u 1:73,"$file" u 1:74,"$file" u 1:75,"$file" u 1:76,"$file" u 1:77,"$file" u 1:78, \
"$file" u 1:79,"$file" u 1:80,"$file" u 1:81,"$file" u 1:82,"$file" u 1:83,"$file" u 1:84,"$file" u 1:85, \
"$file" u 1:86,"$file" u 1:77,"$file" u 1:88,"$file" u 1:89,"$file" u 1:90,"$file" u 1:91,"$file" u 1:92, \
"$file" u 1:93,"$file" u 1:94,"$file" u 1:95,"$file" u 1:96,"$file" u 1:97,"$file" u 1:98,"$file" u 1:99, \
"$file" u 1:100,"$file" u 1:101,"$file" u 1:102,"$file" u 1:103,"$file" u 1:104,"$file" u 1:105,"$file" u 1:106, \
"$file" u 1:107,"$file" u 1:108,"$file" u 1:109,"$file" u 1:110,"$file" u 1:111,"$file" u 1:112,"$file" u 1:113, \
"$file" u 1:114,"$file" u 1:115,"$file" u 1:116,"$file" u 1:117,"$file" u 1:118,"$file" u 1:119,"$file" u 1:120, \
"$file" u 1:121,"$file" u 1:122,"$file" u 1:123,"$file" u 1:124,"$file" u 1:125,"$file" u 1:126,"$file" u 1:127

pause -1 "Showing $file.\nPress enter to quit"
quit
END

gnuplot $cmd

\rm $cmd
